version: "3.7"

networks:
  intercorp-demo-api:

services:
  api:
    build: api
    container_name: api
    secrets:
      - db_datasource  
    volumes:
      - ./intercorp-demo-api:/workspace
      - ~/.m2/repository:/root/.m2/repository
    ports:
      - 8085:8085
    depends_on:
      - oracle-db
    networks:
      - intercorp-demo-api

  oracle-db:
    build:
      context: oracle-db
      dockerfile: Dockerfile
    container_name: db
    environment:
      - SOME_VAR=some_value
    ports:
      - 49161:1521
    networks:
      - intercorp-demo-api
      
secrets:
  db_datasource:
    file: ./ora11db.properties      

