package com.intercorp.demo.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.Objects;

@Entity
@Table(name = "clientes", schema = "system")
public class Customer {

    @ApiModelProperty(value = "customer id, autogenerated", example = "1")
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "clientes_seq")
    @SequenceGenerator(name = "clientes_seq", schema = "system",sequenceName = "clientes_seq", allocationSize = 1)
    private long id;

    @ApiModelProperty(value = "customer's first name", example = "Mason", position = 1)
    @Column(name = "nombre", nullable = false)
    private String firstName;

    @ApiModelProperty(value = "customer's last name", example = "Mount", position = 2)
    @Column(name = "apellido", nullable = false)
    private String lastName;

    @ApiModelProperty(value = "customer's birth date", example = "20/03/1985", position = 4)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    @Column(name = "fecha_nacimiento", nullable = false)
    private LocalDate dateOfBirth;

    @ApiModelProperty(value = "customer's age", example = "33", position = 3)
    @Column(name = "edad", nullable = false)
    private Integer age;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Customer customer = (Customer) o;
        return firstName.equals(customer.firstName) && lastName.equals(customer.lastName) && dateOfBirth.equals(customer.dateOfBirth) && age.equals(customer.age);
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, lastName, dateOfBirth, age);
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", dateOfBirth=" + dateOfBirth +
                ", age=" + age +
                '}';
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }
}
